use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::metadata::SessionMetadata;

pub const MARKER_START: &str = "<!-- sepia:pr-demo:start -->";
pub const MARKER_END: &str = "<!-- sepia:pr-demo:end -->";

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct PrCommentData {
    pub title: String,
    pub description: Option<String>,
    pub video_url: Option<String>,
    pub screenshots: Vec<UploadedScreenshot>,
    pub session_name: String,
    pub commit: Option<String>,
    pub frame_count: u32,
    pub output_fps: u32,
    pub duration_seconds: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct UploadedScreenshot {
    pub label: String,
    pub url: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommentUpsert {
    Create,
    Update { comment_id: u64 },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ExistingComment {
    pub id: u64,
    pub body: String,
}

#[must_use]
pub fn render_pr_comment(data: &PrCommentData) -> String {
    let mut md = String::new();
    md.push_str(MARKER_START);
    md.push_str("\n## Sepia Demo\n\n");

    if let Some(description) = &data.description {
        md.push_str(&format!("> {description}\n\n"));
    }

    if let Some(video_url) = &data.video_url {
        md.push_str("### Recording\n\n");
        md.push_str(video_url);
        md.push_str("\n\n");
    } else {
        md.push_str("_Recording not uploaded yet._\n\n");
    }

    md.push_str(&format!(
        "**Duration:** {:.1}s · **Frames:** {} · **FPS:** {}\n\n",
        data.duration_seconds, data.frame_count, data.output_fps
    ));

    if !data.screenshots.is_empty() {
        md.push_str("<details>\n<summary>Key screenshots</summary>\n\n");
        for screenshot in &data.screenshots {
            md.push_str(&format!(
                "**{}**\n\n![{}]({})\n\n",
                screenshot.label, screenshot.label, screenshot.url
            ));
        }
        md.push_str("</details>\n\n");
    }

    md.push_str("---\n<sub>");
    md.push_str(&format!("Session: `{}`", data.session_name));
    if let Some(commit) = &data.commit {
        md.push_str(&format!(
            " · Commit: `{}`",
            commit.chars().take(7).collect::<String>()
        ));
    }
    md.push_str(" · Generated by Sepia</sub>\n");
    md.push_str(MARKER_END);
    md.push('\n');
    md
}

#[must_use]
pub fn upsert_marked_block(existing_body: &str, sepia_block: &str) -> String {
    let Some(start) = existing_body.find(MARKER_START) else {
        return append_marked_block(existing_body, sepia_block);
    };
    let Some(relative_end) = existing_body[start..].find(MARKER_END) else {
        return append_marked_block(existing_body, sepia_block);
    };
    let end = start + relative_end + MARKER_END.len();
    let mut updated = String::new();
    updated.push_str(existing_body[..start].trim_end());
    if !updated.is_empty() {
        updated.push_str("\n\n");
    }
    updated.push_str(sepia_block.trim());
    let suffix = existing_body[end..].trim_start();
    if !suffix.is_empty() {
        updated.push_str("\n\n");
        updated.push_str(suffix);
    }
    updated.push('\n');
    updated
}

fn append_marked_block(existing_body: &str, sepia_block: &str) -> String {
    let mut updated = existing_body.trim_end().to_string();
    if !updated.is_empty() {
        updated.push_str("\n\n");
    }
    updated.push_str(sepia_block.trim());
    updated.push('\n');
    updated
}

#[must_use]
pub fn upsert_marked_block_at_top(existing_body: &str, sepia_block: &str) -> String {
    let body_without_existing = remove_marked_block(existing_body);
    let mut updated = sepia_block.trim().to_string();
    let rest = body_without_existing.trim();
    if !rest.is_empty() {
        updated.push_str("\n\n");
        updated.push_str(rest);
    }
    updated.push('\n');
    updated
}

#[must_use]
pub fn remove_marked_block(existing_body: &str) -> String {
    let Some(start) = existing_body.find(MARKER_START) else {
        return existing_body.to_string();
    };
    let Some(relative_end) = existing_body[start..].find(MARKER_END) else {
        return existing_body.to_string();
    };
    let end = start + relative_end + MARKER_END.len();
    let mut body = String::new();
    body.push_str(existing_body[..start].trim_end());
    let suffix = existing_body[end..].trim_start();
    if !body.is_empty() && !suffix.is_empty() {
        body.push_str("\n\n");
    }
    body.push_str(suffix);
    body
}

#[must_use]
pub fn choose_comment_upsert(comments: &[ExistingComment]) -> CommentUpsert {
    comments
        .iter()
        .find(|comment| comment.body.contains(MARKER_START))
        .map_or(CommentUpsert::Create, |comment| CommentUpsert::Update {
            comment_id: comment.id,
        })
}

#[must_use]
pub fn content_type_for(path: &std::path::Path) -> &'static str {
    match path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("")
        .to_ascii_lowercase()
        .as_str()
    {
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "webm" => "video/webm",
        "mp4" => "video/mp4",
        _ => "application/octet-stream",
    }
}

#[must_use]
pub fn pr_data_from_metadata(
    metadata: &SessionMetadata,
    video_url: Option<String>,
    uploaded_screenshots: &[UploadedScreenshot],
) -> PrCommentData {
    PrCommentData {
        title: "Sepia Demo".into(),
        description: metadata.description.clone(),
        video_url: video_url.or_else(|| Some(format!("file://{}", metadata.video.display()))),
        screenshots: uploaded_screenshots.to_vec(),
        session_name: metadata
            .video
            .parent()
            .and_then(Path::file_name)
            .and_then(|name| name.to_str())
            .unwrap_or("session")
            .to_string(),
        commit: None,
        frame_count: metadata.frame_count,
        output_fps: metadata.output_fps,
        duration_seconds: metadata.duration_seconds(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_marked_pr_comment() {
        let comment = render_pr_comment(&PrCommentData {
            title: "Sepia Demo".into(),
            description: Some("Windowed browse".into()),
            video_url: Some("https://github.com/user-attachments/assets/abc".into()),
            screenshots: vec![UploadedScreenshot {
                label: "Initial".into(),
                url: "https://example.com/initial.png".into(),
            }],
            session_name: "2026-demo".into(),
            commit: Some("abcdef123456".into()),
            frame_count: 48,
            output_fps: 24,
            duration_seconds: 2.0,
        });
        assert!(comment.contains(MARKER_START));
        assert!(comment.contains("https://github.com/user-attachments/assets/abc"));
        assert!(comment.contains("Commit: `abcdef1`"));
    }

    #[test]
    fn upserts_marked_block_in_existing_body() {
        let existing =
            "Intro\n\n<!-- sepia:pr-demo:start -->\nold\n<!-- sepia:pr-demo:end -->\n\nTail";
        let replacement = "<!-- sepia:pr-demo:start -->\nnew\n<!-- sepia:pr-demo:end -->";
        let updated = upsert_marked_block(existing, replacement);
        assert!(updated.contains("Intro"));
        assert!(updated.contains("new"));
        assert!(updated.contains("Tail"));
        assert!(!updated.contains("old"));
    }

    #[test]
    fn places_marked_block_at_top() {
        let existing =
            "Intro\n\n<!-- sepia:pr-demo:start -->\nold\n<!-- sepia:pr-demo:end -->\n\nTail";
        let replacement = "<!-- sepia:pr-demo:start -->\nnew\n<!-- sepia:pr-demo:end -->";
        let updated = upsert_marked_block_at_top(existing, replacement);
        assert!(updated.starts_with("<!-- sepia:pr-demo:start -->\nnew"));
        assert!(updated.contains("Intro"));
        assert!(updated.contains("Tail"));
        assert!(!updated.contains("old"));
    }

    #[test]
    fn appends_marked_block_when_missing() {
        let updated = upsert_marked_block(
            "Intro",
            "<!-- sepia:pr-demo:start -->\nnew\n<!-- sepia:pr-demo:end -->",
        );
        assert!(updated.starts_with("Intro"));
        assert!(updated.contains("new"));
    }

    #[test]
    fn chooses_update_when_marker_exists() {
        let comments = vec![ExistingComment {
            id: 42,
            body: format!("hello {MARKER_START}"),
        }];
        assert_eq!(
            choose_comment_upsert(&comments),
            CommentUpsert::Update { comment_id: 42 }
        );
    }

    #[test]
    fn maps_upload_content_types() {
        assert_eq!(
            content_type_for(std::path::Path::new("demo.mp4")),
            "video/mp4"
        );
        assert_eq!(
            content_type_for(std::path::Path::new("step.png")),
            "image/png"
        );
    }
}
